sheet "sprites"
    padding 1
    output "public/tiles.png"

description "public/tiles.json"
    template "/opt/spright/share/spright/templates/pixijs.inja"

extrude 1

trim none

input "./rawdata/tiles.png"
    grid-offset 1
    grid-spacing 1
    grid 8x8
        sprite "tiles-00"
        sprite "tiles-01"
        sprite "tiles-02"
        sprite "tiles-03"
        sprite "tiles-04"
        sprite "tiles-05"
        sprite "tiles-06"
    row 1
        sprite "tiles-07"
        sprite "tiles-08"
        sprite "tiles-09"
        sprite "tiles-10"
        sprite "tiles-11"
        sprite "tiles-12"
        sprite "tiles-13"
    row 2
        sprite "tiles-14"
        sprite "tiles-15"
        sprite "tiles-16"
        sprite "tiles-17"
        sprite "tiles-18"
        sprite "tiles-19"
        sprite "tiles-20"
    row 3
        sprite "tiles-21"
        sprite "tiles-22"
